name: build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [simmer]

jobs:
  build:
    name: Check package
    uses: r-simmer/workflows/.github/workflows/build.yml@main
    with:
      extension: true
    secrets: inherit
